version: '3.1'

services:
  db:
    image: postgres:13.1
    restart: always
    env_file:
      database.env
    container_name: db
    volumes:
      - /tmp/data:/var/lib/postgresql/data

  people-service:
    image: rhinoflower/check-in:0.3.0
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=production"
